name: Terraform Plan and Upload to S3

on:
  workflow_dispatch:  # Manual trigger
  push: #on pushing to main brach also
    branches:
      - main  

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=plan.tfplan

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Upload Plan to S3
        run: aws s3 cp plan.tfplan s3://k8assign/terraform-plans/plan-${{ github.sha }}.tfplan
