name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA of the plan to destroy'
        required: true

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download Plan from S3
        run: aws s3 cp s3://k8assign/terraform-plans/plan-${{ github.event.inputs.commit_sha }}.tfplan plan.tfplan

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
