name: Terraform Apply

on:
  workflow_dispatch:  # Manual trigger 

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_key_pair: ${{ secrets.AWS_KEY_PAIR }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  
      
      - name: Terraform Init
        run: terraform init

      - name: Download Plan from S3
        run: aws s3 cp s3://k8assign/terraform-plans/plan-${{ github.sha }}.tfplan plan.tfplan

      - name: Terraform Apply
        run: terraform apply "plan.tfplan"

      